
const ds=[
{id:1,name:'SLYRS Bavarian Whisky Distillery',city:'Schliersee',region:'Bayern',lat:47.736,lng:11.859,type:'Single Malt · Bavarian whisky',desc:'Eine bekannte bayerische Whisky-Destillerie mit regionalem Bezug und breiter Core- und Finish-Range.',styles:['fruchtig','Sherry'],products:[['Einstieg','SLYRS Single Malt Classic','American White Oak · fruchtig, Vanille, Karamell'],['Signature','SLYRS Fifty One','Kräftigere Interpretation des Hausstils'],['Premium / Special','SLYRS Aged 12 Years','Längere Reifung · Vanille, Honig, Frucht und Holz']]},
{id:2,name:'St. Kilian Distillers',city:'Rüdenau',region:'Bayern',lat:49.711,lng:9.180,type:'Single Malt · Pot still',desc:'Deutsche Whisky-Destillerie mit breitem Fassprogramm und milden wie getorften Abfüllungen.',styles:['fruchtig','rauchig'],products:[['Einstieg','Classic – Mild & Fruity','Mild und fruchtig'],['Signature','Peated – Rich & Smoky','Rauchig / getorft'],['Premium / Special','Signature Edition','Limitierte Fasskompositionen']]},
{id:3,name:'Schraml – The Stonewood Distillery',city:'Erbendorf',region:'Bayern',lat:49.84,lng:12.045,type:'Familienbrennerei',desc:'Traditionsreiche Familienbrennerei mit bayerischen Rohstoffen und eigener Whisky-Lagerung.',styles:['fruchtig','Sherry'],products:[['Einstieg','Stonewood 1818','Kernprodukt der Brennerei'],['Signature','Stonewood Woaz','Single Wheat Malt'],['Premium / Special','Stonewood Family Stock','Limitierte Fass-Finishes']]},
{id:4,name:'Elch-Whisky',city:'Thuisbrunn',region:'Bayern',lat:49.697,lng:11.249,type:'Franconian Single Malt',desc:'Fränkischer Whisky mit eigenständigem Rauchprofil und regionalem Charakter.',styles:['rauchig','Sherry'],products:[['Einstieg','Torf vom Dorf','Rauchiger Single Malt'],['Signature','Torfduett','Bourbon- und Akazienfass'],['Premium / Special','Mr. Bär','Längere Reifung · Sherryfass']]},
{id:5,name:'SILD Whisky / Lantenhammer',city:'Hausham',region:'Bayern',lat:47.749,lng:11.842,type:'Single Malt',desc:'Whiskyprojekt mit ungewöhnlichen Reifungsorten und unterschiedlichen Fasskonzepten.',styles:['fruchtig','Sherry'],products:[['Einstieg','SILD Heritage 28','Mild · Getreide · Holz'],['Signature','SILD Triple Cask','Sherry, Portwein und Weinfässer'],['Premium / Special','SILD Single Casks','Limitierte Einzelfässer']]},
{id:6,name:'AYRER’s Whiskydestille',city:'Nürnberg',region:'Bayern',lat:49.456,lng:11.073,type:'Brauerei-Destillerie',desc:'Bio-Brauerei und Brennerei in der Nürnberger Altstadt mit Whisky aus Spezialmalz.',styles:['fruchtig','Sherry'],products:[['Einstieg','AYRER’s RED','Organic Single Malt'],['Signature','AYRER’s TOWER No.1','American White Oak'],['Premium / Special','AYRER’s Sonderabfüllungen','Sherry Finish und weitere Fassprojekte']]},
{id:7,name:'Brennerei Liebl – Coillmór',city:'Bad Kötzting',region:'Bayern',lat:49.176,lng:12.855,type:'Single Malt / Rye / Corn',desc:'Whisky-Destillerie im Bayerischen Wald mit umfangreichem Fassmanagement.',styles:['fruchtig','Sherry'],products:[['Einstieg','Coillmór American Oak','American White Oak'],['Signature','Coillmór Rye','Roggenmalz · nussig · würzig'],['Premium / Special','Coillmór Cask Editions','Wein- und Sonderfässer']]},
{id:8,name:'SinGold Destillerie',city:'Wehringen',region:'Bayern',lat:48.25,lng:10.803,type:'Craft whisky distillery',desc:'Handwerkliche Destillerie südlich von Augsburg mit eigener Produktion und Fassprojekten.',styles:['fruchtig'],products:[['Einstieg','Core Range','Produktwahl noch zu verifizieren'],['Signature','Selected Finish','Produktwahl noch zu verifizieren'],['Premium / Special','Small Cask Project','Optional']]},
{id:9,name:'HeiligenBergFeld Distillery',city:'Herrsching-Widdersberg',region:'Bayern',lat:48.0092,lng:11.1978,type:'Small Batch · Single Cask',desc:'Kleine Brennerei mit bayerischem Malz und Fokus auf Small Batch und Single Cask.',styles:['rauchig','Sherry'],products:[['Einstieg','Selected Small Batch','Bayerischer Single Malt'],['Signature','Sherry Single Cask','Oloroso / Amontillado'],['Premium / Special','Special Edition','Limitierte Einzelfassabfüllung']]},
{id:10,name:'Fränkische Whisky Brennerei Mößlein',city:'Zeilitzheim',region:'Bayern',lat:49.901,lng:10.278,type:'Franconian craft distillery',desc:'Fränkische Whisky-Brennerei; Detailprofil wird im Produktionsdatensatz weiter verifiziert.',styles:['fruchtig'],products:[['Einstieg','Produkt folgt','Noch zu verifizieren'],['Signature','Produkt folgt','Noch zu verifizieren'],['Premium / Special','—','Optional']]}
];
let map,markers=[];function initMap(){if(map)return;map=L.map('map').setView([49,11.4],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(map)}
function showResults(){document.getElementById('results').style.display='block';initMap();setTimeout(()=>map.invalidateSize(),50);render();document.getElementById('results').scrollIntoView({behavior:'smooth'})}function regionBavaria(){document.getElementById('region').value='Bayern';showResults()}
function render(){let q=document.getElementById('query').value.toLowerCase().trim(),reg=document.getElementById('region').value;let rows=ds.filter(d=>(reg==='all'||d.region===reg)&&(!q||(d.name+' '+d.city+' '+d.type+' '+d.styles.join(' ')).toLowerCase().includes(q)));document.getElementById('resultTitle').textContent=reg==='all'?'Whisky in Deutschland':'Whisky in '+reg;document.getElementById('resultCount').textContent=rows.length+' Brennereien in dieser Demo';document.getElementById('list').innerHTML=rows.map(d=>`<div class="card" onclick="focusD(${d.id})"><h3>${d.name}</h3><div class="meta">${d.city} · ${d.type}</div><div class="desc">${d.desc}</div><div class="tags">${d.styles.map(x=>`<span class="tag">${x}</span>`).join('')}</div></div>`).join('');markers.forEach(m=>map.removeLayer(m));markers=[];rows.forEach(d=>{let m=L.marker([d.lat,d.lng]).addTo(map).bindPopup(`<div class="pop"><b>${d.name}</b><br><small>${d.city}</small><br><span class="open" onclick="openProfile(${d.id})">Profil öffnen</span></div>`);m.did=d.id;markers.push(m)});if(rows.length){let g=L.featureGroup(markers);map.fitBounds(g.getBounds().pad(.15))}}
function focusD(id){let d=ds.find(x=>x.id===id),m=markers.find(x=>x.did===id);map.setView([d.lat,d.lng],11);if(m)m.openPopup()}function openProfile(id){let d=ds.find(x=>x.id===id);document.getElementById('home').style.display='none';document.getElementById('profile').style.display='block';pName.textContent=d.name;pLoc.textContent=d.city+', '+d.region;pDesc.textContent=d.desc;pRegion.textContent=d.region;pType.textContent=d.type;pProducts.innerHTML=d.products.map(p=>`<article class="product"><div class="tier">${p[0]}</div><h3>${p[1]}</h3><p>${p[2]}</p><p><span class="gloss" title="Im Live-System öffnet sich hier die Glossar-Erklärung.">Fachbegriffe ⓘ</span></p></article>`).join('');window.scrollTo(0,0)}function backToResults(){profile.style.display='none';home.style.display='block';setTimeout(()=>{map.invalidateSize();document.getElementById('results').scrollIntoView()},30)}
