
const ds=[
{id:1,name:'SLYRS Bavarian Whisky Distillery',city:'Schliersee',region:'Bayern',lat:47.736,lng:11.859,type:'Single Malt · Bavarian whisky',desc:'Eine bekannte bayerische Whisky-Destillerie mit regionalem Bezug und breiter Core- und Finish-Range.',styles:['fruchtig','Sherry'],products:[['Einstieg','SLYRS Single Malt Classic','American White Oak · fruchtig, Vanille, Karamell'],['Signature','SLYRS Fifty One','Kräftigere Interpretation des Hausstils'],['Premium / Special','SLYRS Aged 12 Years','Längere Reifung · Vanille, Honig, Frucht und Holz']]},
{id:2,name:'St. Kilian Distillers',city:'Rüdenau',region:'Bayern',lat:49.711,lng:9.180,type:'Single Malt · Pot still',desc:'Deutsche Whisky-Destillerie mit breitem Fassprogramm und milden wie getorften Abfüllungen.',styles:['fruchtig','rauchig'],products:[['Einstieg','Classic – Mild & Fruity','Mild und fruchtig'],['Signature','Peated – Rich & Smoky','Rauchig / getorft'],['Premium / Special','Signature Edition','Limitierte Fasskompositionen']]},
{id:3,name:'Schraml – The Stonewood Distillery',city:'Erbendorf',region:'Bayern',lat:49.84,lng:12.045,type:'Familienbrennerei',desc:'Traditionsreiche Familienbrennerei mit bayerischen Rohstoffen und eigener Whisky-Lagerung.',styles:['fruchtig','Sherry'],products:[['Einstieg','Stonewood 1818','Kernprodukt der Brennerei'],['Signature','Stonewood Woaz','Single Wheat Malt'],['Premium / Special','Stonewood Family Stock','Limitierte Fass-Finishes']]},
{id:4,name:'Elch-Whisky',city:'Thuisbrunn',region:'Bayern',lat:49.697,lng:11.249,type:'Franconian Single Malt',desc:'Fränkischer Whisky mit eigenständigem Rauchprofil und regionalem Charakter.',styles:['rauchig','Sherry'],products:[['Einstieg','Torf vom Dorf','Rauchiger Single Malt'],['Signature','Torfduett','Bourbon- und Akazienfass'],['Premium / Special','Mr. Bär','Längere Reifung · Sherryfass']]},
{id:5,name:'SILD Whisky / Lantenhammer',city:'Hausham',region:'Bayern',lat:47.749,lng:11.842,type:'Single Malt',desc:'Whiskyprojekt mit ungewöhnlichen Reifungsorten und unterschiedlichen Fasskonzepten.',styles:['fruchtig','Sherry'],products:[['Einstieg','SILD Heritage 28','Mild · Getreide · Holz'],['Signature','SILD Triple Cask','Sherry, Portwein und Weinfässer'],['Premium / Special','SILD Single Casks','Limitierte Einzelfässer']]},
{id:6,name:'AYRER’s Whiskydestille',city:'Nürnberg',region:'Bayern',lat:49.456,lng:11.073,type:'Brauerei-Destillerie',desc:'Bio-Brauerei und Brennerei in der Nürnberger Altstadt mit Whisky aus Spezialmalz.',styles:['fruchtig','Sherry'],products:[['Einstieg','AYRER’s RED','Organic Single Malt'],['Signature','AYRER’s TOWER No.1','American White Oak'],['Premium / Special','AYRER’s Sonderabfüllungen','Sherry Finish und weitere Fassprojekte']]},
{id:7,name:'Brennerei Liebl – Coillmór',city:'Bad Kötzting',region:'Bayern',lat:49.176,lng:12.855,type:'Single Malt / Rye / Corn',desc:'Whisky-Destillerie im Bayerischen Wald mit umfangreichem Fassmanagement.',styles:['fruchtig','Sherry'],products:[['Einstieg','Coillmór American Oak','American White Oak'],['Signature','Coillmór Rye','Roggenmalz · nussig · würzig'],['Premium / Special','Coillmór Cask Editions','Wein- und Sonderfässer']]},
{id:8,name:'SinGold Destillerie',city:'Wehringen',region:'Bayern',lat:48.25,lng:10.803,type:'Craft whisky distillery',desc:'Handwerkliche Destillerie südlich von Augsburg mit eigener Produktion und Fassprojekten.',styles:['fruchtig'],products:[['Einstieg','Core Range','Produktwahl noch zu verifizieren'],['Signature','Selected Finish','Produktwahl noch zu verifizieren'],['Premium / Special','Small Cask Project','Optional']]},
{id:9,name:'HeiligenBergFeld Distillery',city:'Herrsching-Widdersberg',region:'Bayern',lat:48.0092,lng:11.1978,type:'Small Batch · Single Cask',desc:'Kleine Brennerei mit bayerischem Malz und Fokus auf Small Batch und Single Cask.',styles:['rauchig','Sherry'],products:[['Einstieg','Selected Small Batch','Bayerischer Single Malt'],['Signature','Sherry Single Cask','Oloroso / Amontillado'],['Premium / Special','Special Edition','Limitierte Einzelfassabfüllung']]},
{id:10,name:'Fränkische Whisky Brennerei Mößlein',city:'Zeilitzheim',region:'Bayern',lat:49.901,lng:10.278,type:'Franconian craft distillery',desc:'Fränkische Whisky-Brennerei; Detailprofil wird im Produktionsdatensatz weiter verifiziert.',styles:['fruchtig'],products:[['Einstieg','Produkt folgt','Noch zu verifizieren'],['Signature','Produkt folgt','Noch zu verifizieren'],['Premium / Special','—','Optional']]}
];
let map,markers=[];function initMap(){if(map)return;map=L.map('map').setView([49,11.4],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(map)}
function showResults(){document.getElementById('results').style.display='block';initMap();setTimeout(()=>map.invalidateSize(),50);render();document.getElementById('results').scrollIntoView({behavior:'smooth'})}function regionBavaria(){document.getElementById('region').value='Bayern';showResults()}
function render(){let q=document.getElementById('query').value.toLowerCase().trim(),reg=document.getElementById('region').value;let rows=ds.filter(d=>(reg==='all'||d.region===reg)&&(!q||(d.name+' '+d.city+' '+d.type+' '+d.styles.join(' ')).toLowerCase().includes(q)));document.getElementById('resultTitle').textContent=reg==='all'?'Whisky in Deutschland':'Whisky in '+reg;document.getElementById('resultCount').textContent=rows.length+' Brennereien in dieser Demo';document.getElementById('list').innerHTML=rows.map(d=>`<div class="card" onclick="focusD(${d.id})"><h3>${d.name}</h3><div class="meta">${d.city} · ${d.type}</div><div class="desc">${d.desc}</div><div class="tags">${d.styles.map(x=>`<span class="tag">${x}</span>`).join('')}</div></div>`).join('');markers.forEach(m=>map.removeLayer(m));markers=[];rows.forEach(d=>{let m=L.marker([d.lat,d.lng]).addTo(map).bindPopup(`<div class="pop"><b>${d.name}</b><br><small>${d.city}</small><br><span class="open" onclick="openProfile(${d.id})">Profil öffnen</span></div>`);m.did=d.id;markers.push(m)});if(rows.length){let g=L.featureGroup(markers);map.fitBounds(g.getBounds().pad(.15))}}
function focusD(id){let d=ds.find(x=>x.id===id),m=markers.find(x=>x.did===id);map.setView([d.lat,d.lng],11);if(m)m.openPopup()}function openProfile(id){let d=ds.find(x=>x.id===id);document.getElementById('home').style.display='none';document.getElementById('profile').style.display='block';pName.textContent=d.name;pLoc.textContent=d.city+', '+d.region;pDesc.textContent=d.desc;pRegion.textContent=d.region;pType.textContent=d.type;pProducts.innerHTML=d.products.map(p=>`<article class="product"><div class="tier">${p[0]}</div><h3>${p[1]}</h3><p>${p[2]}</p><p><span class="gloss" title="Im Live-System öffnet sich hier die Glossar-Erklärung.">Fachbegriffe ⓘ</span></p></article>`).join('');window.scrollTo(0,0)}function backToResults(){profile.style.display='none';home.style.display='block';setTimeout(()=>{map.invalidateSize();document.getElementById('results').scrollIntoView()},30)}

// Gallery data is intentionally separated from the core distillery records so it can later move to JSON/database storage.
const galleryByDistillery={
  1:[
    ['https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=1600&q=82','Brennerei & Whisky'],
    ['https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=1200&q=82','Fasslager'],
    ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=82','Whisky im Glas'],
    ['https://images.unsplash.com/photo-1528823872057-9c018a7a7553?auto=format&fit=crop&w=1200&q=82','Abfüllung & Produkt'],
    ['https://images.unsplash.com/photo-1527761939622-911909463b7a?auto=format&fit=crop&w=1200&q=82','Holz & Reifung']
  ]
};
let currentGallery=[],galleryIndex=0;
function galleryFor(d){return galleryByDistillery[d.id]||[
 ['https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=1600&q=82','Brennerei'],
 ['https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=1200&q=82','Fasslager'],
 ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=82','Whisky'],
 ['https://images.unsplash.com/photo-1528823872057-9c018a7a7553?auto=format&fit=crop&w=1200&q=82','Produkt']
]}
function renderGallery(d){currentGallery=galleryFor(d);let shown=currentGallery.slice(0,5);document.getElementById('pGallery').innerHTML=shown.map((g,i)=>`<div class="galleryItem" onclick="openGallery(${i})"><img src="${g[0]}" alt="${g[1]}" loading="lazy">${i===shown.length-1&&currentGallery.length>shown.length?`<div class="galleryMore">+${currentGallery.length-shown.length} Fotos</div>`:''}</div>`).join('')}
function openGallery(i=0){if(!currentGallery.length)return;galleryIndex=i;document.getElementById('lightbox').classList.add('open');document.getElementById('lightbox').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';updateLightbox()}
function closeGallery(){document.getElementById('lightbox').classList.remove('open');document.getElementById('lightbox').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function updateLightbox(){let g=currentGallery[galleryIndex];document.getElementById('lbImg').src=g[0];document.getElementById('lbImg').alt=g[1];document.getElementById('lbCaption').textContent=g[1];document.getElementById('lbCount').textContent=(galleryIndex+1)+' / '+currentGallery.length}
function galleryPrev(){galleryIndex=(galleryIndex-1+currentGallery.length)%currentGallery.length;updateLightbox()}
function galleryNext(){galleryIndex=(galleryIndex+1)%currentGallery.length;updateLightbox()}
document.addEventListener('keydown',e=>{if(!document.getElementById('lightbox').classList.contains('open'))return;if(e.key==='Escape')closeGallery();if(e.key==='ArrowLeft')galleryPrev();if(e.key==='ArrowRight')galleryNext()});
document.getElementById('lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox')closeGallery()});

// Extend the existing profile renderer without changing its original behavior.
const _openProfile=openProfile;
openProfile=function(id){_openProfile(id);const d=ds.find(x=>x.id===id);renderGallery(d)};

// Phase-1 product details. Later these records can move into products.json / Supabase.
const productDetails={
 'SLYRS Single Malt Classic':{type:'Single Malt',abv:'43 %',age:'NAS',cask:'American White Oak',peat:'Unpeated',notes:'Fruchtig · Vanille · Karamell',img:'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=900&q=82'},
 'Classic – Mild & Fruity':{type:'Single Malt',abv:'—',age:'—',cask:'—',peat:'Mild / unpeated',notes:'Mild · fruchtig',img:'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=900&q=82'},
 'Peated – Rich & Smoky':{type:'Single Malt',abv:'—',age:'—',cask:'—',peat:'Peated',notes:'Rauchig · kräftig',img:'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=82'}
};
let activeDistillery=null;
const _openProfileProduct=openProfile;
openProfile=function(id){_openProfileProduct(id);activeDistillery=ds.find(x=>x.id===id);pProducts.innerHTML=activeDistillery.products.map((p,i)=>`<article class="product"><div class="tier">${p[0]}</div><h3 class="productLink" onclick="openProduct(${i})">${p[1]}</h3><p>${p[2]}</p><p><span class="gloss" title="Im Live-System öffnet sich hier die Glossar-Erklärung.">Fachbegriffe ⓘ</span></p></article>`).join('')};
function openProduct(i){if(!activeDistillery)return;const p=activeDistillery.products[i],d=productDetails[p[1]]||{};document.getElementById('pmTier').textContent=p[0];document.getElementById('pmName').textContent=p[1];document.getElementById('pmDistillery').textContent=activeDistillery.name+' · '+activeDistillery.city;document.getElementById('pmDesc').textContent=p[2]||'Produktbeschreibung wird ergänzt.';document.getElementById('pmImg').src=d.img||galleryFor(activeDistillery)[2][0];document.getElementById('pmSpecs').innerHTML=[['Whisky-Typ',d.type||'Zu ergänzen'],['Alkohol',d.abv||'Zu ergänzen'],['Alter',d.age||'Zu ergänzen'],['Fass / Reifung',d.cask||'Zu ergänzen'],['Rauch / Torf',d.peat||'Zu ergänzen'],['Profil',d.notes||p[2]||'Zu ergänzen']].map(x=>`<div class="pmSpec"><b>${x[0]}</b>${x[1]}</div>`).join('');document.getElementById('productModal').classList.add('open');document.getElementById('productModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeProduct(){document.getElementById('productModal').classList.remove('open');document.getElementById('productModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.getElementById('productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById('productModal').classList.contains('open'))closeProduct()});
